#Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. 
#The first ten pentagonal numbers are:

#1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

#It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However,
#their difference, 70 − 22 = 48, is not pentagonal.

#Find the pair of pentagonal numbers, Pj and Pk, for which their sum and 
#difference are pentagonal and D = |Pk − Pj| is minimised; 
#what is the value of D?
import math

def pentagen(n):
    for n in range(1,n):
        Pn = (n*(3*n - 1))/2
        pentagonal.append(Pn)

def is_pent(x):
    return ((math.sqrt(24*x + 1) + 1)/6).is_integer()

pentagonal = []
pentagen(100000)
answers =[]
Panswers = []

for i in range(2,len(pentagonal)):
    for n in range (0,i-1):
        if is_pent(pentagonal[i]+pentagonal[n])==True and is_pent(pentagonal[i]-pentagonal[n])==True:
            print('found')
            print('Pk is',int(pentagonal[i]),'Pj is',int(pentagonal[n]))
            print('D is',int(pentagonal[i]-pentagonal[n]))
          
