#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

#Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
#It can be verified that T285 = P165 = H143 = 40755.

#Find the next triangle number that is also pentagonal and hexagonal.

# we know that every Hexagonal number is a triangle number so we can iterate through through hexagonal numbers to find the next one that is pentagonal
import math

def is_pent(x):
    return ((math.sqrt(24*x + 1) + 1)/6).is_integer()
   

def Problem45():
    n = 144
    pent = 0 
    while pent == 0:
        H = n*(2*n - 1)
        if is_pent(H) == True:
            pent = H
        else:
            n+=1
    print('The next number that is Trangular, Pentagonal, and Hexagonal is',pent)

Problem45()
